### PR TITLE
Fix Bad state: No element error in PuroVersion constructor by using firstWhereOrNull

### LINKED ISSUE #79: Error when using puro standalone with an absolute path
I get a warning/error message when I try to use puro standalone with an absolute path, even though it seems to work fine.
```
~/Projects/puro_project > /Users/username/Projects/puro_project/bin/puro --version
[W] Error while parsing package configBad state: No element
    #0      ListBase.firstWhere (dart:collection/list.dart:132)
    #1      PuroVersion._getRootFromPackageConfig (package:puro/src/version.dart:83)
    <asynchronous suspension>
    #2      PuroVersion.provider.<anonymous closure> (package:puro/src/version.dart:139)
    <asynchronous suspension>
    #3      VersionCommand.run (package:puro/src/commands/version.dart:35)
    <asynchronous suspension>
    #4      CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #5      main (package:puro/src/cli.dart:256)
    <asynchronous suspension>

[i] Puro 1.4.6 (standalone/darwin-x64)
    Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_x64"
```

But when I use puro with a relative path, I get no warning/error message.
```
~/Projects/puro_project > ./bin/puro --version
[i] Puro 1.4.6 (standalone/darwin-x64)
    Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_x64"
```

When I install puro and then use it with an absolute path, it also works just fine.
```
~/Projects/puro_project > /Users/username/.puro/bin/puro --version
[i] Puro 1.4.6 (distribution/darwin-x64)
    Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_x64"
```

In this case I used puro standalone 1.4.6 on MacOS.
It seems that this problem only occurs in the standalone version.

### PR DESCRIPTION
**Pull request by Shreemanarjun**
In the PuroVersion constructor, we were using firstWhere to find the 'puro' package in the packages list. However, if the 'puro' package is not found, firstWhere would throw a Bad state: No element error. To fix this, I've replaced firstWhere with firstWhereOrNull, which returns null if no element matches the predicate.

This change ensures that we don't crash with a Bad state: No element error when the 'puro' package is not found in the packages list.
Let me know if you'd like me to make any changes!
 It should fix #79 & #80

### CODE REVIEW

File: puro/lib/src/version.dart [hunk 1]
```diff
@@ -80,8 +81,8 @@ class PuroVersion {
       final packages = packageData['packages'] as List<dynamic>;
       final puroPackage = packages
           .cast<Map<String, dynamic>>()
-          .firstWhere((e) => e['name'] == 'puro');
-      final rootUri = Uri.parse(puroPackage['rootUri'] as String);
+          .firstWhereOrNull((e) => e['name'] == 'puro');
+      final rootUri = Uri.parse(puroPackage?['rootUri'] as String);
```
Comment (pingbird) [inline puro/lib/src/version.dart:85]: the `as String` will fail if puroPackage is null, you should just check and return null here

**Review by pingbird — CHANGES_REQUESTED** [review]

File: puro/lib/src/version.dart (hunk 1 above)
Comment (Shreemanarjun) [reply puro/lib/src/version.dart:88]: Fixed Now.

Comment (pingbird) [reply puro/lib/src/version.dart:88]: the `&& puroPackage?['rootUri'] == null` part is unnecessary, it will always be null if puroPackage is null

Comment (Shreemanarjun) [reply puro/lib/src/version.dart:88]: updated code as required.

**Review by passsy — APPROVED** [review]

File: puro/lib/src/version.dart [hunk 2]
```diff
@@ -80,8 +81,11 @@ class PuroVersion {
       final packages = packageData['packages'] as List<dynamic>;
       final puroPackage = packages
           .cast<Map<String, dynamic>>()
-          .firstWhere((e) => e['name'] == 'puro');
-      final rootUri = Uri.parse(puroPackage['rootUri'] as String);
+          .firstWhereOrNull((e) => e['name'] == 'puro');
+      if (puroPackage == null) {
+        return null;
+      }
+      final rootUri = Uri.parse(puroPackage?['rootUri'] as String);
```
Comment (pingbird) [inline puro/lib/src/version.dart:88]: One final thing and it should be ready, the `?` in `final rootUri = Uri.parse(puroPackage?['rootUri'] as String);` on line 88 generates a warning because puroPackage can't be null anymore, it can be removed

Comment (Shreemanarjun) [reply puro/lib/src/version.dart]: Done.

**Comment by rehlma** [comment]
The warning is gone 🎉

**Comment by pingbird** [comment]
Sorry I haven't been able to push this yet, CI is failing because the instance on CircleCI is now an m1 mac
